"use client";
import type { CSSProperties } from "react";
import type { ComponentType } from "react";
import type { IconProps as PhosphorIconProps, IconWeight } from "@phosphor-icons/react";
import * as Phosphor from "@phosphor-icons/react";

interface IconProps {
  size?: number | string;
  className?: string;
  color?: string;
  style?: CSSProperties;
  weight?: IconWeight;
  onClick?: (e: React.MouseEvent) => void;
  [key: string]: any;
}

/**
 * Envuelve un ícono real de Phosphor preservando el nombre de export bootstrap/lucide legado,
 * para que los archivos que importan de aquí no tengan que tocarse. Por defecto renderiza en
 * "duotone" (decisión de producto, 2026-09) — pero si el call site ya pasa `weight` explícito
 * (Sidebar/Topbar alternan "regular"/"duotone" para el estado activo/inactivo), se respeta.
 */
function wrap(Component: ComponentType<PhosphorIconProps>) {
  function Icon({ size = 20, weight, strokeWidth, absoluteStrokeWidth, ...rest }: IconProps) {
    return <Component size={size} weight={weight ?? "duotone"} {...rest} />;
  }
  Icon.displayName = `PhosphorIcon(${(Component as any).displayName || "?"})`;
  return Icon;
}

const P = Phosphor as any;

export const Activity = wrap(P.Pulse);
export const AlertCircle = wrap(P.WarningCircle);
export const AlertOctagon = wrap(P.WarningOctagon);
export const AlertTriangle = wrap(P.Warning);
export const Archive = wrap(P.Archive);
export const ArrowDown = wrap(P.ArrowDown);
export const ArrowDownToLine = wrap(P.ArrowLineDown);
export const ArrowLeft = wrap(P.ArrowLeft);
export const ArrowLeftRight = wrap(P.ArrowsLeftRight);
export const ArrowRight = wrap(P.ArrowRight);
export const ArrowUp = wrap(P.ArrowUp);
export const ArrowUpRight = wrap(P.ArrowUpRight);
export const ArrowUpToLine = wrap(P.ArrowLineUp);
export const AtSign = wrap(P.At);
export const AudioLines = wrap(P.WaveSine);
export const Award = wrap(P.Medal);
export const Ban = wrap(P.Prohibit);
export const BarChart3 = wrap(P.ChartBar);
export const Bell = wrap(P.Bell);
export const BellOff = wrap(P.BellSlash);
export const Bold = wrap(P.TextB);
export const Bolt = wrap(P.Lightning);
export const Bot = wrap(P.Robot);
export const Briefcase = wrap(P.Briefcase);
export const Building2 = wrap(P.Buildings);
export const Cake = wrap(P.Cake);
export const Calendar = wrap(P.Calendar);
export const CalendarClock = wrap(P.CalendarBlank);
export const CalendarDays = wrap(P.Calendar);
export const CalendarOff = wrap(P.CalendarX);
export const CalendarX2 = wrap(P.CalendarX);
export const Camera = wrap(P.Camera);
export const Check = wrap(P.Check);
export const CheckCheck = wrap(P.Checks);
export const CheckCircle2 = wrap(P.CheckCircle);
export const CheckSquare = wrap(P.CheckSquare);
export const ChevronDown = wrap(P.CaretDown);
export const ChevronLeft = wrap(P.CaretLeft);
export const ChevronRight = wrap(P.CaretRight);
export const ChevronUp = wrap(P.CaretUp);
export const ChevronsLeft = wrap(P.CaretDoubleLeft);
export const ChevronsRight = wrap(P.CaretDoubleRight);
export const Circle = wrap(P.Circle);
export const CircleCheck = wrap(P.CheckCircle);
export const CircleDot = wrap(P.Record);
export const ClipboardList = wrap(P.ClipboardText);
export const Clock = wrap(P.Clock);
export const Code = wrap(P.Code);
export const Coffee = wrap(P.Coffee);
export const Cog = wrap(P.Gear);
export const Command = wrap(P.Command);
export const Construction = wrap(P.Wrench);
export const Copy = wrap(P.Copy);
export const CornerDownLeft = wrap(P.ArrowBendDownLeft);
export const Crown = wrap(P.Crown);
export const DollarSign = wrap(P.CurrencyDollar);
export const Download = wrap(P.DownloadSimple);
export const Edit = wrap(P.Pencil);
export const Edit3 = wrap(P.PencilSimple);
export const ExternalLink = wrap(P.ArrowSquareOut);
export const Eye = wrap(P.Eye);
export const EyeOff = wrap(P.EyeSlash);
export const File = wrap(P.File);
export const FileArchive = wrap(P.FileZip);
export const FileAudio = wrap(P.FileAudio);
export const FileCode = wrap(P.FileCode);
export const FileImage = wrap(P.FileImage);
export const FileSpreadsheet = wrap(P.FileXls);
export const FileText = wrap(P.FileText);
export const FileType = wrap(P.FileText);
export const FileVideo = wrap(P.FileVideo);
export const Filter = wrap(P.Funnel);
export const Flag = wrap(P.Flag);
export const Flame = wrap(P.Fire);
export const Folder = wrap(P.Folder);
export const FolderKanban = wrap(P.Kanban);
export const FolderOpen = wrap(P.FolderOpen);
export const FolderPlus = wrap(P.FolderPlus);
export const Forward = wrap(P.ArrowBendUpRight);
export const Gauge = wrap(P.Gauge);
export const Gift = wrap(P.Gift);
export const GitMerge = wrap(P.GitMerge);
export const Globe = wrap(P.Globe);
export const GraduationCap = wrap(P.GraduationCap);
export const GripVertical = wrap(P.DotsSixVertical);
export const Hand = wrap(P.Hand);
export const HardDrive = wrap(P.HardDrive);
export const Hash = wrap(P.Hash);
export const Heading2 = wrap(P.TextHTwo);
export const Heart = wrap(P.Heart);
export const Home = wrap(P.House);
export const Image = wrap(P.Image);
export const Inbox = wrap(P.Tray);
export const Info = wrap(P.Info);
export const Italic = wrap(P.TextItalic);
export const KeyRound = wrap(P.Key);
export const Languages = wrap(P.Translate);
export const LayoutDashboard = wrap(P.SquaresFour);
export const LayoutGrid = wrap(P.GridFour);
export const LayoutList = wrap(P.ListBullets);
export const Link = wrap(P.Link);
export const Link2 = wrap(P.LinkSimple);
export const List = wrap(P.List);
export const ListOrdered = wrap(P.ListNumbers);
export const ListTree = wrap(P.TreeStructure);
export const Loader2 = wrap(P.CircleNotch);
export const Lock = wrap(P.Lock);
export const LogOut = wrap(P.SignOut);
export const Mail = wrap(P.Envelope);
export const MailOpen = wrap(P.EnvelopeOpen);
export const MapPin = wrap(P.MapPin);
export const Maximize2 = wrap(P.ArrowsOut);
export const Megaphone = wrap(P.Megaphone);
export const MessageSquare = wrap(P.ChatText);
export const MessageSquareMore = wrap(P.ChatDots);
export const MessagesSquare = wrap(P.ChatCenteredText);
export const Mic = wrap(P.Microphone);
export const MicOff = wrap(P.MicrophoneSlash);
export const Minimize2 = wrap(P.ArrowsIn);
export const Monitor = wrap(P.Monitor);
export const MonitorUp = wrap(P.MonitorPlay);
export const Moon = wrap(P.MoonStars);
export const MoreHorizontal = wrap(P.DotsThree);
export const MoreVertical = wrap(P.DotsThreeVertical);
export const Move = wrap(P.ArrowsOutCardinal);
export const MousePointer2 = wrap(P.Cursor);
export const Network = wrap(P.ShareNetwork);
export const Palette = wrap(P.Palette);
export const PanelLeftClose = wrap(P.SidebarSimple);
export const PanelLeftOpen = wrap(P.Sidebar);
export const Paperclip = wrap(P.Paperclip);
export const PartyPopper = wrap(P.Confetti);
export const Pause = wrap(P.Pause);
export const Pencil = wrap(P.Pencil);
export const Percent = wrap(P.Percent);
export const Phone = wrap(P.Phone);
export const PhoneCall = wrap(P.PhoneOutgoing);
export const PhoneIncoming = wrap(P.PhoneIncoming);
export const PhoneMissed = wrap(P.PhoneX);
export const PhoneOff = wrap(P.PhoneX);
export const PictureInPicture2 = wrap(P.PictureInPicture);
export const PieChart = wrap(P.ChartPie);
export const Pin = wrap(P.PushPin);
export const PinOff = wrap(P.PushPinSlash);
export const Play = wrap(P.Play);
export const Plus = wrap(P.Plus);
export const Presentation = wrap(P.Presentation);
export const Quote = wrap(P.Quotes);
export const Redo2 = wrap(P.ArrowClockwise);
export const RefreshCw = wrap(P.ArrowsClockwise);
export const Reply = wrap(P.ArrowBendUpLeft);
export const RotateCcw = wrap(P.ArrowCounterClockwise);
export const Rows = wrap(P.Rows);
export const Save = wrap(P.FloppyDisk);
export const ScreenShare = wrap(P.Monitor);
export const ScreenShareOff = wrap(P.Monitor);
export const Search = wrap(P.MagnifyingGlass);
export const Send = wrap(P.PaperPlaneTilt);
export const Server = wrap(P.HardDrives);
export const Settings = wrap(P.Gear);
export const Share2 = wrap(P.ShareNetwork);
export const Shield = wrap(P.Shield);
export const ShieldCheck = wrap(P.ShieldCheck);
export const Smartphone = wrap(P.DeviceMobile);
export const Smile = wrap(P.Smiley);
export const SmilePlus = wrap(P.Smiley);
export const Sparkle = wrap(P.Sparkle);
export const Sparkles = wrap(P.Sparkle);
export const Square = wrap(P.Square);
export const Star = wrap(P.Star);
export const StickyNote = wrap(P.Note);
export const Sun = wrap(P.Sun);
export const Tag = wrap(P.Tag);
export const Target = wrap(P.Target);
export const ThumbsUp = wrap(P.ThumbsUp);
export const Trash = wrap(P.Trash);
export const Trash2 = wrap(P.TrashSimple);
export const TrendingUp = wrap(P.TrendUp);
export const Trophy = wrap(P.Trophy);
export const Undo2 = wrap(P.ArrowUUpLeft);
export const Upload = wrap(P.UploadSimple);
export const User = wrap(P.User);
export const UserCheck = wrap(P.UserCircleCheck ?? P.UserCircle);
export const UserCircle = wrap(P.UserCircle);
export const UserCircle2 = wrap(P.UserCircle);
export const UserCog = wrap(P.UserGear);
export const UserPlus = wrap(P.UserPlus);
export const UserX = wrap(P.UserMinus);
export const Users = wrap(P.Users);
export const Users2 = wrap(P.UsersThree);
export const Video = wrap(P.VideoCamera);
export const VideoOff = wrap(P.VideoCameraSlash);
export const Volume2 = wrap(P.SpeakerHigh);
export const VolumeX = wrap(P.SpeakerSlash);
export const Wand2 = wrap(P.MagicWand);
export const Webhook = wrap(P.Plug);
export const WifiOff = wrap(P.WifiSlash);
export const Wine = wrap(P.Wine);
export const X = wrap(P.X);
export const XCircle = wrap(P.XCircle);
export const Zap = wrap(P.Lightning);
export const ZapOff = wrap(P.LightningSlash);
export const ZoomIn = wrap(P.MagnifyingGlassPlus);
export const ZoomOut = wrap(P.MagnifyingGlassMinus);
export const AppWindow = wrap(P.AppWindow);
export const CaretDown = wrap(P.CaretDown);
export const CaretLeft = wrap(P.CaretLeft);
export const CaretRight = wrap(P.CaretRight);
export const ChartLine = wrap(P.ChartLine);
export const ChatCircle = wrap(P.ChatCircle);
export const CircleDashed = wrap(P.CircleDashed);
export const CurrencyDollar = wrap(P.CurrencyDollar);
export const Envelope = wrap(P.Envelope);
export const Fire = wrap(P.Fire);
export const FolderSimple = wrap(P.FolderSimple);
export const Gear = wrap(P.Gear);
export const HouseSimple = wrap(P.HouseSimple);
export const Lightning = wrap(P.Lightning);
export const MagicWand = wrap(P.MagicWand);
export const MagnifyingGlass = wrap(P.MagnifyingGlass);
export const MoonStars = wrap(P.MoonStars);
export const SignOut = wrap(P.SignOut);
export const Tray = wrap(P.Tray);
export const TrendUp = wrap(P.TrendUp);
export const Warning = wrap(P.Warning);
export const ArrowSquareOut = wrap(P.ArrowSquareOut);
export const WarningCircle = wrap(P.WarningCircle);
